curso_main_homepage:
    path:     /hello/{name}/{edad}
    defaults: { _controller: CursoMainBundle:Default:index }
curso_main_help:
    path:     /ayuda/{tema}
    defaults: { _controller: CursoMainBundle:Default:ayuda }
curso_main_nosotros:
    path:     /nosotros/{nombre}/{apellidos}/{nacimiento}
    defaults: { _controller: CursoMainBundle:Info:nosotros, nombre:Julio, apellidos:widmann, nacimiento:arequipa }
curso_main_info:
    path:     /info/{pagina}
    defaults: { _controller: CursoMainBundle:Info:pagina_estatica,pagina:quien }